apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-api
  template:
    metadata:
      labels:
        app: task-tracker-api
    spec:
      containers:
      - name: task-tracker-api
        image: task-tracker-api:${{ github.sha }}
        imagePullPolicy: Always                   
        ports:
        - containerPort: 8080
