apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-api
  template:
    metadata:
      labels:
        app: task-tracker-api
    spec:
      containers:
      - name: task-tracker-api
        image: ghcr.io/blixoww/task-tracker-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 7070
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 7070
          initialDelaySeconds: 30
          periodSeconds: 10
